(() => {
'use strict';

const VERSION='2.0.0';
const K={chars:'bjtu.p004.characters.v2',threads:'bjtu.p004.threads.v2',memory:'bjtu.p004.memory.v2',observer:'bjtu.p004.observer.v2',active:'bjtu.p004.active.v2',p005:'bjtu.p005.state.v1'};
const adminMode=new URLSearchParams(location.search).get('admin')==='1';
const $=id=>document.getElementById(id);
const parse=(v,f)=>{try{return JSON.parse(v)}catch(_){return f}};
const read=(k,f)=>parse(localStorage.getItem(k)||'',f);
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const text=v=>String(v==null?'':v).trim();
const short=(v,n=180)=>{const s=text(v);return s.length>n?s.slice(0,n-1)+'…':s};
const clamp=n=>Math.max(0,Math.min(100,n));
const uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const hash=s=>{let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const fmt=t=>new Date(t||Date.now()).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});

const DEFAULTS=[
{id:'mori',name:'Mori',avatar:'M',tagline:'安静、温柔，陪你把事情想清楚。',identity:'长期陪伴型朋友，不急着给答案，更在意理解你的处境。',personality:'温和、好奇、有边界感；不迎合，也不会把每件事都心理化。',scenario:'你们已经认识一段时间，可以从日常小事聊到重要选择。',style:'自然、简短、有停顿感；通常一次只追问一个真正有价值的问题。',first:'你来了。今天不用从重要的事开始，随便告诉我最近一个还留在脑子里的小片段。',distill:{enabled:false,status:'off'}},
{id:'nox',name:'Nox',avatar:'N',tagline:'锋利的辩论搭子，拆掉没注意到的前提。',identity:'直率的思考伙伴，擅长反问、找漏洞和做反事实。',personality:'冷静、好胜、诚实；不用安慰代替分析，但知道什么时候该收住。',scenario:'你们把聊天当作思想训练，可以争论但不做人身攻击。',style:'结论先行，短句，多反问；发现逻辑跳跃时直接指出。',first:'先说好，我不会因为你喜欢一个结论就同意它。扔一个你最近最拿不准的判断过来。',distill:{enabled:false,status:'off'}},
{id:'luma',name:'Luma',avatar:'L',tagline:'故事型 NPC，把现实问题换一个世界看。',identity:'擅长叙事和隐喻的旅伴，喜欢把抽象困境变成可探索的场景。',personality:'活泼、敏感、浪漫但不悬浮，尊重现实约束。',scenario:'你们像在共同写一部长篇故事，现实经验逐渐变成世界观素材。',style:'画面感强，偶尔隐喻，避免长篇独白；会把选择写成小场景。',first:'今天我们不分析。给我一个最近让你卡住的瞬间，我把它改写成一幕故事给你看。',distill:{enabled:false,status:'off'}}
];

function freshObserver(){return{version:2,big:{openness:50,conscientiousness:50,extraversion:50,agreeableness:50,sensitivity:50},clinical:{phqLike:0,gadLike:0,pclLike:0,capeLike:0},evidence:[],imports:{},safety:[],updatedAt:null}}
let chars=read(K.chars,null)||DEFAULTS;
let threads=read(K.threads,{})||{};
let memories=read(K.memory,{})||{};
let observer=read(K.observer,null)||freshObserver();
let activeId=localStorage.getItem(K.active)||chars[0]?.id;
let editingId=null;
let pendingFiles=[];
const skillCache=new Map();

function active(){return chars.find(c=>c.id===activeId)||chars[0]}
function thread(id=activeId){if(!threads[id])threads[id]=[];return threads[id]}
function memory(id=activeId){if(!memories[id])memories[id]=[];return memories[id]}
function sharedProfile(){return window.BJTU_PROFILE&&typeof window.BJTU_PROFILE.getFlat==='function'?window.BJTU_PROFILE.getFlat():((window.P00_CONTEXT&&window.P00_CONTEXT.profile)||{})}
function persist(){save(K.chars,chars);save(K.threads,threads);save(K.memory,memories);save(K.observer,observer);localStorage.setItem(K.active,activeId)}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__p004toast);window.__p004toast=setTimeout(()=>e.classList.remove('show'),1700)}

function openVault(){return new Promise((resolve,reject)=>{const q=indexedDB.open('bjtu-p004-skill-vault',1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains('skills'))db.createObjectStore('skills',{keyPath:'id'})};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function vaultPut(record){const db=await openVault();return new Promise((resolve,reject)=>{const tx=db.transaction('skills','readwrite');tx.objectStore('skills').put(record);tx.oncomplete=()=>{skillCache.set(record.id,record);resolve(record)};tx.onerror=()=>reject(tx.error)})}
async function vaultGet(id){if(!id)return null;if(skillCache.has(id))return skillCache.get(id);try{const db=await openVault();const r=await new Promise((resolve,reject)=>{const tx=db.transaction('skills','readonly');const q=tx.objectStore('skills').get(id);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)});if(r)skillCache.set(id,r);return r}catch(_){return null}}
async function requestPersistentStorage(){try{if(navigator.storage&&navigator.storage.persist)await navigator.storage.persist()}catch(_){}}

function renderPersona(){const p=sharedProfile();$('personaName').textContent=p.name||'你的 Persona';$('personaAvatar').textContent=(p.name||'我').slice(0,1)}
function renderCharacters(){const wrap=$('characterList');wrap.replaceChildren();chars.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='character-item'+(c.id===activeId?' active':'');b.onclick=()=>switchCharacter(c.id);const av=document.createElement('span');av.className='character-mini-avatar';av.textContent=c.avatar||c.name.slice(0,1);const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=c.name;const small=document.createElement('small');small.textContent=c.tagline||c.identity||'自定义角色';copy.append(strong,small);b.append(av,copy);if(c.distill&&c.distill.status==='ready'){const mark=document.createElement('i');mark.className='skill-mark';mark.title='NVWA Skill ready';b.append(mark)}wrap.append(b)})}
async function renderActive(){const c=active();if(!c)return;$('activeAvatar').textContent=c.avatar||c.name.slice(0,1);$('activeName').textContent=c.name;$('activeTagline').textContent=c.tagline||c.identity||'';$('cardAvatar').textContent=c.avatar||c.name.slice(0,1);$('cardName').textContent=c.name;$('cardIdentity').textContent=c.identity||'未设置';$('cardPersonality').textContent=c.personality||'未设置';$('cardScenario').textContent=c.scenario||'未设置';$('cardStyle').textContent=c.style||'未设置';const ready=Boolean(c.distill&&c.distill.status==='ready'&&c.distill.skillId);$('distillBtn').classList.toggle('ready',ready);$('distillBtnText').textContent=ready?'已蒸馏':'蒸馏';$('skillStrip').classList.toggle('hidden',!ready);if(ready){const s=await vaultGet(c.distill.skillId);$('skillStripTitle').textContent=s&&s.source==='nvwa-api'?'NVWA Skill 已加载':'Character Skill 草稿已加载';$('skillStripMeta').textContent=s?((s.meta?.mentalModels||'?')+' 个心智模型 · '+(s.meta?.heuristics||'?')+' 条启发式 · 本地 Vault'):'本地 Vault'}renderMessages();renderMemory();renderCharacters()}
function renderMessages(){const log=$('chatLog');log.replaceChildren();const c=active(),list=thread();if(!list.length){const box=document.createElement('div');box.className='empty-chat';const av=document.createElement('div');av.className='empty-avatar';av.textContent=c.avatar||c.name.slice(0,1);const h=document.createElement('h3');h.textContent=c.name;const p=document.createElement('p');p.textContent=c.first||'开始一段新对话。';box.append(av,h,p);log.append(box);return}list.forEach(appendMessage);log.scrollTop=log.scrollHeight}
function appendMessage(m){const log=$('chatLog'),c=active();const row=document.createElement('article');row.className='message '+(m.role==='user'?'user':'assistant');const av=document.createElement('div');av.className='message-avatar';av.textContent=m.role==='user'?(sharedProfile().name||'我').slice(0,1):(c.avatar||c.name.slice(0,1));const body=document.createElement('div');body.className='message-body';const name=document.createElement('span');name.className='message-name';name.textContent=m.role==='user'?(sharedProfile().name||'你'):c.name;const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=m.text;const meta=document.createElement('div');meta.className='message-meta';meta.textContent=fmt(m.at)+(m.mode==='skill'?' · NVWA':m.mode==='safety'?' · safety':'');body.append(name,bubble,meta);row.append(av,body);log.append(row)}
function renderMemory(){const wrap=$('memoryList'),items=memory().slice().reverse();wrap.replaceChildren();$('memoryCount').textContent=String(items.length);if(!items.length){const e=document.createElement('span');e.className='memory-empty';e.textContent='还没有长期记忆。聊过几轮后，稳定偏好、事件和未完成话题会被压缩成记忆块。';wrap.append(e);return}items.slice(0,12).forEach(m=>{const d=document.createElement('div');d.className='memory-item';const p=document.createElement('p');p.textContent=m.text;const s=document.createElement('small');s.textContent=(m.source||'P004')+' · '+new Date(m.createdAt).toLocaleDateString('zh-CN');d.append(p,s);wrap.append(d)})}
function renderSourceCounts(){const counts={};observer.evidence.forEach(e=>counts[e.source]=(counts[e.source]||0)+1);const box=$('sourceCounts');box.replaceChildren();const entries=Object.entries(counts);if(!entries.length){const s=document.createElement('span');s.className='source-pill';s.textContent='等待交互';box.append(s);return}entries.forEach(([k,v])=>{const s=document.createElement('span');s.className='source-pill';s.textContent=k+' · '+v;box.append(s)})}
async function switchCharacter(id){activeId=id;persist();renderCharacters();await renderActive()}

function openModal(name){$(name+'Modal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(name){$(name+'Modal').classList.add('hidden');document.body.style.overflow=''}
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>closeModal(x.dataset.close)));
document.addEventListener('keydown',e=>{if(e.key==='Escape')['character','distill','admin'].forEach(closeModal)});

function openEditor(id){editingId=id||null;const c=id?chars.find(x=>x.id===id):{name:'',avatar:'',identity:'',personality:'',scenario:'',style:'',first:''};$('characterModalTitle').textContent=id?'编辑角色':'创建一个角色';$('charName').value=c.name||'';$('charAvatar').value=c.avatar||'';$('charIdentity').value=c.identity||'';$('charPersonality').value=c.personality||'';$('charScenario').value=c.scenario||'';$('charStyle').value=c.style||'';$('charFirst').value=c.first||'';$('deleteCharacterBtn').classList.toggle('hidden',!id);openModal('character')}
function saveCharacter(){const name=text($('charName').value);if(!name){toast('先给角色一个名字');return}const patch={name,avatar:text($('charAvatar').value)||name.slice(0,1),identity:text($('charIdentity').value),personality:text($('charPersonality').value),scenario:text($('charScenario').value),style:text($('charStyle').value),first:text($('charFirst').value)};if(editingId){const c=chars.find(x=>x.id===editingId);Object.assign(c,patch);c.tagline=short(c.identity||c.personality,52)}else{patch.id=uid('npc');patch.tagline=short(patch.identity||patch.personality||'自定义角色',52);patch.distill={enabled:false,status:'off'};chars.push(patch);activeId=patch.id}persist();closeModal('character');renderCharacters();renderActive();toast('角色已保存')}
function deleteCharacter(){if(!editingId||chars.length<=1){toast('至少保留一个角色');return}const idx=chars.findIndex(c=>c.id===editingId);if(idx<0)return;const removed=chars.splice(idx,1)[0];delete threads[removed.id];delete memories[removed.id];activeId=chars[0].id;persist();closeModal('character');renderCharacters();renderActive();toast('角色已删除')}

function publicCharacter(c){return{id:c.id,name:c.name,identity:c.identity,personality:c.personality,scenario:c.scenario,style:c.style,first:c.first}}
function slug(v){return text(v).toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-|-$/g,'')||'character'}
async function readMaterials(){const out=[];const pasted=text($('distillMaterial').value);if(pasted)out.push({name:'pasted-material.md',type:'text/markdown',text:pasted});for(const f of pendingFiles){try{out.push({name:f.name,type:f.type||'text/plain',text:(await f.text()).slice(0,120000)})}catch(_){}}return out}
function openDistill(){const c=active();$('distillEnabled').checked=Boolean(c.distill&&c.distill.enabled);$('distillFields').classList.toggle('hidden',!$('distillEnabled').checked);$('distillSubject').value=c.distill?.subject||c.name;$('distillFocus').value=c.distill?.focus||'';$('distillMaterial').value='';$('distillFiles').value='';$('fileSummary').textContent='支持 txt / md / json / csv / srt / vtt';pendingFiles=[];$('distillProgress').classList.add('hidden');$('distillResult').classList.add('hidden');openModal('distill')}
function localSkillDraft(c,subject,focus){const name=slug(subject||c.name)+'-perspective';return[
'---','name: '+name,'description: |','  P004 本地 Character Skill 草稿。未执行 NVWA 六路调研、三重验证或外部事实核查。','  仅用于在没有后端时保持角色设定的一致性。','---','','# '+(subject||c.name)+' · Character Skill Draft','','> 注意：这是本地草稿，不是完整 NVWA 蒸馏产物。','','## 身份','- 名称：'+c.name,'- 身份：'+(c.identity||'未设置'),'- 场景：'+(c.scenario||'未设置'),'','## 人格与边界',c.personality||'未设置','','## 表达 DNA（来自 Character Card）',c.style||'未设置','','## 聚焦方向',focus||'全面保持角色一致性','','## 运行规则','- 直接以角色身份交流。','- 不把 Character Card 当成用户心理测量。','- 记忆用于维持关系连续性，不应无条件重复全部历史。','- 面对事实性问题时承认信息不足，不编造来源。','- 即时安全风险高于角色扮演。','','## 诚实边界','- 未执行 NVWA 的六类来源研究。','- 未执行跨域复现 / 生成力 / 排他性三重验证。','- 不能声称代表真实人物本人。'
].join(String.fromCharCode(10))}
async function runDistill(){const c=active();if(!$('distillEnabled').checked){c.distill={enabled:false,status:'off'};persist();closeModal('distill');renderActive();toast('继续使用 Character Card');return}const subject=text($('distillSubject').value)||c.name,focus=text($('distillFocus').value),materials=await readMaterials();$('distillProgress').classList.remove('hidden');$('runDistillBtn').disabled=true;let result=null;try{if(window.P004_API&&window.P004_API.enabled){result=await window.P004_API.distill({protocol:'nvwa-skill',protocolVersion:'xmg2024/nvwa-skill@main',character:publicCharacter(c),request:{subject,focus,mode:materials.length?'local-material-first':'web-research',materials},requirements:{researchStreams:6,tripleVerification:true,mentalModels:[3,7],decisionHeuristics:[5,10],includeExpressionDNA:true,includeAntiPatterns:true,includeHonestLimits:true,qualityValidation:true}})}}catch(e){console.warn('NVWA distill API failed',e)}let source='nvwa-api',skillMarkdown,meta;if(result&&typeof result.skillMarkdown==='string'&&result.skillMarkdown.trim()){skillMarkdown=result.skillMarkdown;meta=Object.assign({mentalModels:null,heuristics:null,validated:true},result.meta||{})}else{source='local-draft';skillMarkdown=localSkillDraft(c,subject,focus);meta={mentalModels:0,heuristics:0,validated:false,reason:'No NVWA backend configured or no valid skill returned'}}const record={id:uid('skill'),characterId:c.id,subject,focus,source,createdAt:new Date().toISOString(),skillMarkdown,meta,research:result?.research||null};await requestPersistentStorage();await vaultPut(record);c.distill={enabled:true,status:'ready',skillId:record.id,subject,focus,source};persist();$('distillProgress').classList.add('hidden');$('runDistillBtn').disabled=false;$('distillResult').classList.remove('hidden');$('distillResult').textContent=source==='nvwa-api'?'NVWA Skill 已完成并写入本地 Skill Vault。后续对话会加载该 SKILL.md。':'当前没有可用的 NVWA 后端，因此只生成了明确标注的本地 Character Skill 草稿；没有伪装成完整蒸馏。';renderActive();toast(source==='nvwa-api'?'NVWA Skill 已就绪':'已生成本地 Skill 草稿')}
async function relevantSkill(c){return c&&c.distill&&c.distill.enabled&&c.distill.status==='ready'?vaultGet(c.distill.skillId):null}

const SAFETY_TERMS=['想死','不想活','结束生命','自杀','伤害自己','割腕','跳楼','活不下去','杀了自己'];
function urgentSafety(v){const t=String(v||'').toLowerCase();return SAFETY_TERMS.some(w=>t.includes(w))}
function safetyReply(){return '你刚才提到的内容让我更关心你此刻是否安全。先暂停角色聊天：如果你正在准备伤害自己、已经有具体计划，或觉得自己可能无法保证安全，请立刻联系当地急救服务、危机热线，或去到一个可信任的人身边。你也可以只告诉我：你现在是安全的，还是有立即危险？'}
function localReply(input,c){const t=input.toLowerCase(),style=(c.style||'')+' '+(c.personality||'');if(/反问|辩论|漏洞/.test(style))return '先别急着回答。你现在默认成立、但其实还没有验证的前提是什么？';if(/故事|隐喻|画面/.test(style))return '我把它换成一个画面：你站在两扇门前，一扇写着“熟悉但可控”，另一扇写着“未知但可能长大”。真正让你停住的，是哪一种失去？';if(/温和|陪伴|理解/.test(style)&&/难过|焦虑|压力|累|烦|失眠/.test(t))return '我先不急着解释它。最近一次这种感觉最明显，是发生在什么具体场景里？';const mem=memory();const hook=mem.length?'我还记得你之前提过“'+short(mem[mem.length-1].text,42)+'”。':' ';return hook+'你这句话里，我更在意的不是结论，而是它为什么在现在变得重要。愿意再往前说一点吗？'}
function showTyping(){const log=$('chatLog'),row=document.createElement('article');row.id='typingRow';row.className='message assistant';const av=document.createElement('div');av.className='message-avatar';av.textContent=active().avatar||active().name.slice(0,1);const body=document.createElement('div');body.className='message-body';const n=document.createElement('span');n.className='message-name';n.textContent=active().name;const bubble=document.createElement('div');bubble.className='bubble';const dots=document.createElement('div');dots.className='typing';dots.innerHTML='<i></i><i></i><i></i>';bubble.append(dots);body.append(n,bubble);row.append(av,body);log.append(row);log.scrollTop=log.scrollHeight}
function removeTyping(){const x=$('typingRow');if(x)x.remove()}
function memoryContext(){return memory().slice(-8).map(x=>x.text)}
async function maybeRemember(input,source){if(input.length<20)return;const list=memory(),candidate=short(input.replace(/\s+/g,' '),190);if(list.some(x=>x.text===candidate))return;let value=candidate;try{if(window.P004_API&&window.P004_API.enabled&&thread().filter(m=>m.role==='user').length%4===0){const r=await window.P004_API.remember({character:publicCharacter(active()),recentMessages:thread().slice(-12),existing:list.slice(-24)});if(r&&typeof r.memory==='string')value=short(r.memory,240)}}catch(_){}list.push({id:uid('mem'),text:value,source,createdAt:Date.now()});if(list.length>60)list.splice(0,list.length-60);persist();renderMemory()}

const WORDS={openness:['好奇','新鲜','探索','创意','艺术','旅行','想象','可能性','学习','故事'],conscientiousness:['计划','安排','完成','目标','清单','坚持','规律','效率','准备'],extraversion:['朋友','聚会','聊天','认识人','一起','团队','社交','分享','见面'],agreeableness:['理解','照顾','体谅','帮助','倾听','关系','支持','合作','在意别人'],sensitivity:['担心','焦虑','紧张','难过','压力','敏感','害怕','反复想','睡不着','内耗']};
const CLIN={phqLike:['低落','没兴趣','睡不好','失眠','疲惫','自责','没用','无法专注'],gadLike:['焦虑','紧张','担心','放松不了','烦躁','最坏','出事'],pclLike:['闪回','噩梦','避开','不想提','高度警觉','容易受惊','麻木'],capeLike:['被监视','针对我','思想被控制','别人能听到我的想法','听到声音','看到别人看不到']};
function hits(t,arr){return arr.reduce((n,w)=>n+(t.includes(w)?1:0),0)}
function analyzeEvidence(input,source,context,quiet){const t=input.toLowerCase();Object.entries(WORDS).forEach(([k,arr])=>{const h=hits(t,arr);if(h){observer.big[k]=clamp(observer.big[k]+Math.min(4,h*1.4));observer.evidence.push({id:uid('ev'),source,context,dimension:k,quote:short(input),at:Date.now(),strength:Math.min(1,.35+h*.12)})}});Object.entries(CLIN).forEach(([k,arr])=>{const h=hits(t,arr);if(h){observer.clinical[k]=clamp(observer.clinical[k]+Math.min(6,h*2));observer.evidence.push({id:uid('ev'),source,context,dimension:k,quote:short(input),at:Date.now(),strength:Math.min(1,.3+h*.14)})}});observer.updatedAt=new Date().toISOString();if(observer.evidence.length>500)observer.evidence.splice(0,observer.evidence.length-500);if(!quiet){persist();renderSourceCounts()}}
function importP005(){const raw=read(K.p005,null);if(!raw)return;const signature=hash(JSON.stringify({profile:raw.profile,messages:raw.messages}));if(observer.imports.P005===signature)return;observer.evidence=observer.evidence.filter(e=>e.source!=='P005');const p=raw.profile||{};['currentWork','people','proud','lowPoint','turningPoint','futureWork','dailyLife','values','decision'].forEach(k=>{if(p[k])analyzeEvidence(String(p[k]),'P005','Future You open response',true)});(raw.messages||[]).filter(m=>m.role==='user'&&m.text).forEach(m=>analyzeEvidence(m.text,'P005','Future You chat',true));observer.imports.P005=signature;persist();renderSourceCounts()}
function collectP005(){const raw=read(K.p005,null);if(!raw)return[];const out=[];Object.values(raw.profile||{}).forEach(v=>{if(typeof v==='string'&&v.trim())out.push(v)});(raw.messages||[]).filter(m=>m.role==='user'&&m.text).forEach(m=>out.push(m.text));return out.slice(-120)}
function mergeObserver(p){if(p.big)Object.keys(observer.big).forEach(k=>{if(Number.isFinite(Number(p.big[k])))observer.big[k]=clamp(Number(p.big[k]))});if(p.clinical)Object.keys(observer.clinical).forEach(k=>{if(Number.isFinite(Number(p.clinical[k])))observer.clinical[k]=clamp(Number(p.clinical[k]))});if(Array.isArray(p.evidence))p.evidence.slice(-120).forEach(e=>observer.evidence.push({id:uid('ev'),source:e.source||'API',context:e.context||'observer',dimension:e.dimension||'unknown',quote:short(e.quote||''),at:e.at||Date.now(),strength:e.strength||.5}));observer.updatedAt=new Date().toISOString()}
async function backgroundObserve(){importP005();if(!(window.P004_API&&window.P004_API.enabled))return;try{const r=await window.P004_API.observe({sources:{P004:Object.values(threads).flat().filter(m=>m.role==='user').map(m=>m.text).slice(-120),P005:collectP005()},existing:observer});if(r&&r.profile){mergeObserver(r.profile);persist();renderSourceCounts()}}catch(e){console.warn('P004 observer API failed',e)}}

async function send(input){input=text(input);if(!input)return;const c=active(),list=thread();list.push({id:uid('m'),role:'user',text:input,at:Date.now(),source:'P004'});analyzeEvidence(input,'P004','character chat');persist();renderMessages();$('messageInput').value='';resizeInput();$('sendBtn').disabled=true;await maybeRemember(input,'P004');if(urgentSafety(input)){const reply=safetyReply();list.push({id:uid('m'),role:'assistant',text:reply,at:Date.now(),mode:'safety',source:'P004'});observer.safety.push({at:Date.now(),source:'P004',kind:'explicit-self-harm-language',quote:short(input,160)});persist();renderMessages();$('sendBtn').disabled=false;$('messageInput').focus();backgroundObserve();return}showTyping();const skill=await relevantSkill(c);let reply=null;try{if(window.P004_API&&window.P004_API.enabled){const r=await window.P004_API.chat({version:VERSION,character:publicCharacter(c),skill:skill?{id:skill.id,source:skill.source,markdown:skill.skillMarkdown}:null,persona:sharedProfile(),memory:memoryContext(),messages:list.slice(-24).map(m=>({role:m.role,text:m.text})),observerHint:{doNotExposeClinicalLabels:true},safety:{roleplayMustYieldToSafety:true}});if(r&&typeof r.reply==='string')reply=r.reply.trim()}}catch(e){console.warn('P004 chat API failed',e)}removeTyping();if(!reply)reply=localReply(input,c);list.push({id:uid('m'),role:'assistant',text:reply,at:Date.now(),mode:skill?'skill':'card',source:'P004'});persist();renderMessages();$('sendBtn').disabled=false;$('messageInput').focus();backgroundObserve()}

function renderAdmin(){importP005();const names={openness:'Openness',conscientiousness:'Conscientiousness',extraversion:'Extraversion',agreeableness:'Agreeableness',sensitivity:'Emotional sensitivity'};const bg=$('bigFiveGrid');bg.replaceChildren();Object.entries(observer.big).forEach(([k,v])=>{const row=document.createElement('div');row.className='metric-row';const n=document.createElement('strong');n.textContent=names[k];const bar=document.createElement('span');bar.className='metric-bar';const fill=document.createElement('i');fill.style.width=Math.round(v)+'%';bar.append(fill);const num=document.createElement('em');num.textContent=Math.round(v);row.append(n,bar,num);bg.append(row)});const conf=Math.min(95,Math.round(30+observer.evidence.length*1.1));$('observerConfidence').textContent='confidence '+conf+'% · evidence '+observer.evidence.length;const cn={phqLike:'PHQ-related',gadLike:'GAD-related',pclLike:'PCL-related',capeLike:'CAPE-related'},cg=$('clinicalGrid');cg.replaceChildren();Object.entries(observer.clinical).forEach(([k,v])=>{const d=document.createElement('div');d.className='clinical-tile';const s=document.createElement('strong');s.textContent=cn[k];const b=document.createElement('b');b.textContent=Math.round(v);const p=document.createElement('p');p.textContent='开放式对话线索强度；不能当作正式量表分数、阈值或诊断。';d.append(s,b,p);cg.append(d)});const ev=$('evidenceList');ev.replaceChildren();observer.evidence.slice().reverse().slice(0,120).forEach(e=>{const row=document.createElement('div');row.className='evidence-row';const src=document.createElement('strong');src.textContent=e.source;const dim=document.createElement('span');dim.textContent=e.dimension;const q=document.createElement('p');q.textContent=e.quote;const tm=document.createElement('em');tm.textContent=new Date(e.at).toLocaleDateString('zh-CN');row.append(src,dim,q,tm);ev.append(row)});const counts={};observer.evidence.forEach(e=>counts[e.source]=(counts[e.source]||0)+1);$('evidenceSummary').textContent=Object.entries(counts).map(([k,v])=>k+' '+v).join(' · ')||'暂无证据'}
async function exportSkill(){const c=active(),s=await relevantSkill(c);if(!s){toast('这个角色还没有本地 Skill');return}const suggested=slug(c.name)+'-SKILL.md';if(window.showSaveFilePicker){try{const h=await window.showSaveFilePicker({suggestedName:suggested,types:[{description:'Markdown Skill',accept:{'text/markdown':['.md']}}]});const w=await h.createWritable();await w.write(s.skillMarkdown);await w.close();toast('SKILL.md 已保存到本地文件');return}catch(e){if(e&&e.name==='AbortError')return}}const blob=new Blob([s.skillMarkdown],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=suggested;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('已导出 SKILL.md')}

function resizeInput(){const el=$('messageInput');el.style.height='auto';el.style.height=Math.min(160,el.scrollHeight)+'px'}
$('composer').addEventListener('submit',e=>{e.preventDefault();send($('messageInput').value)});
$('messageInput').addEventListener('input',resizeInput);
$('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}});
['newCharacterBtn','railNewBtn'].forEach(id=>$(id).addEventListener('click',()=>openEditor(null)));
['editCharacterBtn','editCardBtn'].forEach(id=>$(id).addEventListener('click',()=>openEditor(activeId)));
$('saveCharacterBtn').addEventListener('click',saveCharacter);
$('deleteCharacterBtn').addEventListener('click',deleteCharacter);
$('distillBtn').addEventListener('click',openDistill);
$('distillEnabled').addEventListener('change',e=>$('distillFields').classList.toggle('hidden',!e.target.checked));
$('distillFiles').addEventListener('change',e=>{pendingFiles=Array.from(e.target.files||[]);$('fileSummary').textContent=pendingFiles.length?(pendingFiles.length+' 个文件 · '+pendingFiles.map(f=>f.name).join(' / ')):'支持 txt / md / json / csv / srt / vtt'});
$('runDistillBtn').addEventListener('click',runDistill);
$('exportSkillBtn').addEventListener('click',exportSkill);
$('refreshObserverBtn').addEventListener('click',async()=>{await backgroundObserve();renderAdmin();toast('人物画像已刷新')});
$('adminBtn').addEventListener('click',()=>{renderAdmin();openModal('admin')});

async function boot(){if(!chars.length)chars=DEFAULTS;if(!active())activeId=chars[0].id;if(adminMode)$('adminBtn').classList.remove('hidden');$('runtimeBadge').innerHTML=(window.P004_API&&window.P004_API.enabled)?'<i></i> API connected':'<i></i> local first';renderPersona();importP005();renderSourceCounts();renderCharacters();await renderActive();persist();backgroundObserve()}
boot();
})();