(function(){
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const ranks=(arr,n=5)=>(arr||[]).slice(0,n).map((x,i)=>'<div class="rank-row"><b>'+(i+1)+'</b><span>'+esc(x)+'</span></div>').join('');
const chips=arr=>(arr||[]).map(x=>'<span class="report-chip">'+esc(x)+'</span>').join('');
const valuePills=items=>(items||[]).slice(0,4).map(x=>'<span class="value-pill" style="--v:'+esc(x.color||'#d8b15c')+'"><i></i>'+esc(x.label)+'</span>').join('');
function quote(text,fallback){return esc((text||'').trim()||fallback)}
window.P001Report={html(result,code,style='diary'){
 const hz=result.future_horizon_label||'未来',cur=result.current_rank_labels||[],ideal=result.ideal_rank_labels||[],vals=result.value_rank_items||[];
 const curTop=cur.slice(0,3),idealTop=ideal.slice(0,3);const distance=result.future_distance_0_100??'—',overlap=result.future_overlap_percent??'—';
 return '<div class="report-composite">'+
 '<article class="share-poster '+style+'"><div class="poster-blob b1"></div><div class="poster-blob b2"></div><header><span class="poster-kicker">A NOTE ACROSS TIME</span><span class="poster-code">'+esc(code)+'</span></header><h2>现在的我，<br>正在走向怎样的自己？</h2><div class="poster-self-grid"><section class="poster-self now"><small>现在的我</small><strong>'+esc(curTop[0]||'正在认识自己')+'</strong><div>'+curTop.slice(1).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></section><div class="poster-arrow">→</div><section class="poster-self ideal"><small>理想的我</small><strong>'+esc(idealTop[0]||'仍在想象')+'</strong><div>'+idealTop.slice(1).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></section></div><section class="poster-values"><small>我最看重</small><div>'+valuePills(vals)+'</div></section><section class="poster-future"><div><small>与'+esc(hz)+'的距离感</small><strong>'+esc(distance)+'</strong><span>/ 100</span></div><div class="mini-orb-pair"><i class="mini-now"></i><i class="mini-future" style="margin-left:'+(Math.min(100,Number(overlap)||0)*-.18)+'px"></i></div><div><small>重叠</small><strong>'+esc(overlap)+'%</strong></div></section><section class="poster-message"><small>我想送给'+esc(hz)+'的自己</small><p>“'+quote(result.future_message,'继续往前，也别忘了照顾自己。')+'”</p></section><section class="poster-message reply"><small>我希望'+esc(hz)+'的自己对现在的我说</small><p>“'+quote(result.future_reply,'你已经走得比想象中远了。')+'”</p></section><footer>写给'+esc(hz)+'的我 · '+esc(code)+'</footer></article>'+
 '<div class="report-details"><section><h3>现在的我 · Top</h3>'+ranks(cur)+'</section><section><h3>理想的我 · Top</h3>'+ranks(ideal)+'</section><section><h3>我最看重</h3>'+valuePills(vals)+'</section><section><h3>'+esc(hz)+'的一天</h3><div class="report-chips">'+chips(result.future_context_labels||[])+'</div></section><section><h3>可能卡住我的地方</h3><div class="report-chips">'+chips(result.obstacle_labels||[])+'</div><p class="report-plan-line">如果卡住，我先：<b>'+esc(result.action_label||'—')+'</b></p></section><section><h3>两种未来连接感</h3><p>距离感：'+esc(distance)+' / 100　·　圆形重叠：'+esc(overlap)+'%</p></section></div></div>';
}};
})();